disabled_rules:
  - trailing_comma
  - todo

line_length:
  warning: 270
  error: 300
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 1500
  error: 1600

type_body_length:
  warning: 1500
  error: 1600

identifier_name:
  min_length: 1
  max_length: 60

function_body_length:
  warning: 80
  error: 100
