import Foundation

struct MockData {
    private static let currentYear = Calendar.current.component(.year, from: Date())

    // MARK: - Chase Cards

    static let chaseCards: [CreditCard] = [
        CreditCard(
            id: "chase-sapphire-preferred",
            name: "Chase Sapphire Preferred",
            issuer: "Chase",
            network: .visa,
            annualFee: 95,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .dining, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .streaming, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .onlineShopping, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .travel, multiplier: 5, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 60000, bonusType: .points, spendRequirement: 4000, timeframeDays: 90, description: "60,000 points after $4,000 in 3 months"),
            imageColor: "#1A1F71",
            imageURL: "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/sapphire_preferred_card.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "chase-sapphire-reserve",
            name: "Chase Sapphire Reserve",
            issuer: "Chase",
            network: .visa,
            annualFee: 550,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .dining, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .travel, multiplier: 5, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .streaming, multiplier: 10, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 60000, bonusType: .points, spendRequirement: 4000, timeframeDays: 90, description: "60,000 points after $4,000 in 3 months"),
            imageColor: "#1A1F71",
            imageURL: "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/sapphire_reserve_card_Halo.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "chase-freedom-flex",
            name: "Chase Freedom Flex",
            issuer: "Chase",
            network: .mastercard,
            annualFee: 0,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .dining, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .drugstore, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .travel, multiplier: 5, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: [
                RotatingCategory(quarter: 1, year: MockData.currentYear, categories: [.grocery], multiplier: 5, isPercentage: false, cap: 1500, activationRequired: true),
                RotatingCategory(quarter: 2, year: MockData.currentYear, categories: [.gas, .homeImprovement], multiplier: 5, isPercentage: false, cap: 1500, activationRequired: true),
                RotatingCategory(quarter: 3, year: MockData.currentYear, categories: [.dining, .drugstore], multiplier: 5, isPercentage: false, cap: 1500, activationRequired: true),
                RotatingCategory(quarter: 4, year: MockData.currentYear, categories: [.amazon, .paypal, .wholesale], multiplier: 5, isPercentage: false, cap: 1500, activationRequired: true),
            ],
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 20000, bonusType: .points, spendRequirement: 500, timeframeDays: 90, description: "20,000 points after $500 in 3 months"),
            imageColor: "#0066B2",
            imageURL: "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/freedom_flex_card_alt.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "chase-freedom-unlimited",
            name: "Chase Freedom Unlimited",
            issuer: "Chase",
            network: .visa,
            annualFee: 0,
            rewardType: .points,
            baseReward: 1.5,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .dining, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .drugstore, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .travel, multiplier: 5, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 20000, bonusType: .points, spendRequirement: 500, timeframeDays: 90, description: "20,000 points after $500 in 3 months"),
            imageColor: "#0066B2",
            imageURL: "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/freedom_unlimited_card_alt.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "chase-freedom-rise",
            name: "Chase Freedom Rise",
            issuer: "Chase",
            network: .visa,
            annualFee: 0,
            rewardType: .points,
            baseReward: 1.5,
            baseIsPercentage: true,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#0066B2",
            imageURL: "https://cdn.chase.com/content/dam/jpmc-marketplace/card-art/freedom_rise_alt_card2.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "chase-ink-business-preferred",
            name: "Ink Business Preferred",
            issuer: "Chase",
            network: .visa,
            annualFee: 95,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 3, isPercentage: false, cap: 150000, capPeriod: .yearly),
                CategoryReward(category: .shipping, multiplier: 3, isPercentage: false, cap: 150000, capPeriod: .yearly),
                CategoryReward(category: .advertising, multiplier: 3, isPercentage: false, cap: 150000, capPeriod: .yearly),
                CategoryReward(category: .internet, multiplier: 3, isPercentage: false, cap: 150000, capPeriod: .yearly),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 100000, bonusType: .points, spendRequirement: 8000, timeframeDays: 90, description: "100,000 points after $8,000 in 3 months"),
            imageColor: "#1A1F71",
            imageURL: "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/ink_preferred_card.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "chase-ink-business-cash",
            name: "Ink Business Cash",
            issuer: "Chase",
            network: .visa,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .officeSupplies, multiplier: 5, isPercentage: true, cap: 25000, capPeriod: .yearly),
                CategoryReward(category: .internet, multiplier: 5, isPercentage: true, cap: 25000, capPeriod: .yearly),
                CategoryReward(category: .gas, multiplier: 2, isPercentage: true, cap: 25000, capPeriod: .yearly),
                CategoryReward(category: .dining, multiplier: 2, isPercentage: true, cap: 25000, capPeriod: .yearly),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 75000, bonusType: .points, spendRequirement: 6000, timeframeDays: 90, description: "$750 bonus after $6,000 in 3 months"),
            imageColor: "#0066B2",
            imageURL: "https://www.chase.com/content/dam/jpmc-marketplace/card-art/ink_cash_card.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "chase-ink-business-unlimited",
            name: "Ink Business Unlimited",
            issuer: "Chase",
            network: .visa,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1.5,
            baseIsPercentage: true,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 75000, bonusType: .points, spendRequirement: 6000, timeframeDays: 90, description: "$750 bonus after $6,000 in 3 months"),
            imageColor: "#0066B2",
            imageURL: "https://www.chase.com/content/dam/jpmc-marketplace/card-art/ink_unlimited_card.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "amazon-prime-visa",
            name: "Amazon Prime Rewards Visa",
            issuer: "Chase",
            network: .visa,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .amazon, multiplier: 5, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .wholeFoods, multiplier: 5, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 2, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .gas, multiplier: 2, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .transit, multiplier: 2, isPercentage: true, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 200, bonusType: .cashback, spendRequirement: 0, timeframeDays: 0, description: "$200 Amazon Gift Card instantly upon approval"),
            imageColor: "#232F3E",
            imageURL: "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/prime-visa.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "united-quest",
            name: "United Quest Card",
            issuer: "Chase",
            network: .visa,
            annualFee: 250,
            rewardType: .miles,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .streaming, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 70000, bonusType: .miles, spendRequirement: 4000, timeframeDays: 90, description: "70,000 miles after $4,000 in 3 months"),
            imageColor: "#0032A0",
            imageURL: "https://www.chase.com/content/dam/jpmc-marketplace/card-art/united_quest_card_tilted.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "southwest-priority",
            name: "Southwest Rapid Rewards Priority",
            issuer: "Chase",
            network: .visa,
            annualFee: 149,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .transit, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .internet, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .streaming, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 50000, bonusType: .points, spendRequirement: 1000, timeframeDays: 90, description: "50,000 points after $1,000 in 3 months"),
            imageColor: "#304CB2",
            imageURL: "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/swa_priority_card-2.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "marriott-bonvoy-boundless",
            name: "Marriott Bonvoy Boundless",
            issuer: "Chase",
            network: .visa,
            annualFee: 95,
            rewardType: .points,
            baseReward: 2,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 6, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 85000, bonusType: .points, spendRequirement: 4000, timeframeDays: 90, description: "85,000 points after $4,000 in 3 months"),
            imageColor: "#8C1D40",
            imageURL: "https://www.chase.com/content/dam/jpmc-marketplace/card-art/marriott-bonvoy-boundless-card.png",
            lastUpdated: Date()
        ),
    ]

    // MARK: - American Express Cards

    static let amexCards: [CreditCard] = [
        CreditCard(
            id: "amex-gold",
            name: "American Express Gold",
            issuer: "American Express",
            network: .amex,
            annualFee: 250,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .dining, multiplier: 4, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 4, isPercentage: false, cap: 25000, capPeriod: .yearly),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 60000, bonusType: .points, spendRequirement: 6000, timeframeDays: 180, description: "60,000 points after $6,000 in 6 months"),
            imageColor: "#B4975A",
            imageURL: "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/gold-card.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "amex-platinum",
            name: "The Platinum Card",
            issuer: "American Express",
            network: .amex,
            annualFee: 695,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 5, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 80000, bonusType: .points, spendRequirement: 8000, timeframeDays: 180, description: "80,000 points after $8,000 in 6 months"),
            imageColor: "#C0C0C0",
            imageURL: "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/platinum-card.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "amex-green",
            name: "American Express Green",
            issuer: "American Express",
            network: .amex,
            annualFee: 150,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .transit, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 40000, bonusType: .points, spendRequirement: 3000, timeframeDays: 180, description: "40,000 points after $3,000 in 6 months"),
            imageColor: "#006B54",
            imageURL: "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/green-card.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "amex-blue-cash-preferred",
            name: "Blue Cash Preferred",
            issuer: "American Express",
            network: .amex,
            annualFee: 95,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .grocery, multiplier: 6, isPercentage: true, cap: 6000, capPeriod: .yearly),
                CategoryReward(category: .streaming, multiplier: 6, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .transit, multiplier: 3, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .gas, multiplier: 3, isPercentage: true, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 350, bonusType: .cashback, spendRequirement: 3000, timeframeDays: 180, description: "$350 back after $3,000 in 6 months"),
            imageColor: "#006FCF",
            imageURL: "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/blue-cash-preferred.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "amex-blue-cash-everyday",
            name: "Blue Cash Everyday",
            issuer: "American Express",
            network: .amex,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .grocery, multiplier: 3, isPercentage: true, cap: 6000, capPeriod: .yearly),
                CategoryReward(category: .gas, multiplier: 3, isPercentage: true, cap: 6000, capPeriod: .yearly),
                CategoryReward(category: .onlineShopping, multiplier: 3, isPercentage: true, cap: 6000, capPeriod: .yearly),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 200, bonusType: .cashback, spendRequirement: 2000, timeframeDays: 180, description: "$200 back after $2,000 in 6 months"),
            imageColor: "#006FCF",
            imageURL: "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/blue-cash-everyday.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "amex-everyday",
            name: "Amex EveryDay",
            issuer: "American Express",
            network: .amex,
            annualFee: 0,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .grocery, multiplier: 2, isPercentage: false, cap: 6000, capPeriod: .yearly),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 10000, bonusType: .points, spendRequirement: 2000, timeframeDays: 180, description: "10,000 points after $2,000 in 6 months"),
            imageColor: "#006FCF",
            imageURL: "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/amex-everyday.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "amex-everyday-preferred",
            name: "Amex EveryDay Preferred",
            issuer: "American Express",
            network: .amex,
            annualFee: 95,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .grocery, multiplier: 3, isPercentage: false, cap: 6000, capPeriod: .yearly),
                CategoryReward(category: .gas, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 15000, bonusType: .points, spendRequirement: 2000, timeframeDays: 180, description: "15,000 points after $2,000 in 6 months"),
            imageColor: "#006FCF",
            imageURL: "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/amex-everyday-preferred.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "delta-skymiles-gold",
            name: "Delta SkyMiles Gold",
            issuer: "American Express",
            network: .amex,
            annualFee: 150,
            rewardType: .miles,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 50000, bonusType: .miles, spendRequirement: 3000, timeframeDays: 180, description: "50,000 miles after $3,000 in 6 months"),
            imageColor: "#003366",
            imageURL: "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/gold-delta-skymiles.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "delta-skymiles-platinum",
            name: "Delta SkyMiles Platinum",
            issuer: "American Express",
            network: .amex,
            annualFee: 350,
            rewardType: .miles,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 90000, bonusType: .miles, spendRequirement: 4000, timeframeDays: 180, description: "90,000 miles after $4,000 in 6 months"),
            imageColor: "#003366",
            imageURL: "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/platinum-delta-skymiles.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "delta-skymiles-reserve",
            name: "Delta SkyMiles Reserve",
            issuer: "American Express",
            network: .amex,
            annualFee: 650,
            rewardType: .miles,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 90000, bonusType: .miles, spendRequirement: 6000, timeframeDays: 180, description: "90,000 miles after $6,000 in 6 months"),
            imageColor: "#722F37",
            imageURL: "https://icm.aexp-static.com/acquisition/card-art/NUS000000237_480x304_straight_withname.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "hilton-honors",
            name: "Hilton Honors",
            issuer: "American Express",
            network: .amex,
            annualFee: 0,
            rewardType: .points,
            baseReward: 3,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 7, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 5, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 5, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .gas, multiplier: 5, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 80000, bonusType: .points, spendRequirement: 2000, timeframeDays: 180, description: "80,000 points after $2,000 in 6 months"),
            imageColor: "#104C97",
            imageURL: "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/hilton-honors.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "hilton-honors-surpass",
            name: "Hilton Honors Surpass",
            issuer: "American Express",
            network: .amex,
            annualFee: 150,
            rewardType: .points,
            baseReward: 3,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 12, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 6, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 6, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .gas, multiplier: 6, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 130000, bonusType: .points, spendRequirement: 3000, timeframeDays: 180, description: "130,000 points after $3,000 in 6 months"),
            imageColor: "#104C97",
            imageURL: "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/hilton-honors-surpass.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "hilton-honors-aspire",
            name: "Hilton Honors Aspire",
            issuer: "American Express",
            network: .amex,
            annualFee: 550,
            rewardType: .points,
            baseReward: 3,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 14, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 7, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 175000, bonusType: .points, spendRequirement: 6000, timeframeDays: 180, description: "175,000 points after $6,000 in 6 months"),
            imageColor: "#104C97",
            imageURL: "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/hilton-honors-aspire.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "marriott-bonvoy-brilliant",
            name: "Marriott Bonvoy Brilliant",
            issuer: "American Express",
            network: .amex,
            annualFee: 650,
            rewardType: .points,
            baseReward: 2,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 6, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 95000, bonusType: .points, spendRequirement: 6000, timeframeDays: 180, description: "95,000 points after $6,000 in 6 months"),
            imageColor: "#8C1D40",
            imageURL: "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/marriott-bonvoy-brilliant.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "amex-blue-business-plus",
            name: "Blue Business Plus",
            issuer: "American Express",
            network: .amex,
            annualFee: 0,
            rewardType: .points,
            baseReward: 2,
            baseIsPercentage: false,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 15000, bonusType: .points, spendRequirement: 3000, timeframeDays: 90, description: "15,000 points after $3,000 in 3 months"),
            imageColor: "#006FCF",
            imageURL: nil,
            lastUpdated: Date()
        ),
    ]

    // MARK: - Citi Cards

    static let citiCards: [CreditCard] = [
        CreditCard(
            id: "citi-double-cash",
            name: "Citi Double Cash",
            issuer: "Citi",
            network: .mastercard,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 2,
            baseIsPercentage: true,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 200, bonusType: .cashback, spendRequirement: 1500, timeframeDays: 180, description: "$200 back after $1,500 in 6 months"),
            imageColor: "#003B70",
            imageURL: "https://www.citi.com/CRD/images/citi-double-cash/citi-double-cash_222x140.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "citi-custom-cash",
            name: "Citi Custom Cash",
            issuer: "Citi",
            network: .mastercard,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .dining, multiplier: 5, isPercentage: true, cap: 500, capPeriod: .monthly),
                CategoryReward(category: .grocery, multiplier: 5, isPercentage: true, cap: 500, capPeriod: .monthly),
                CategoryReward(category: .gas, multiplier: 5, isPercentage: true, cap: 500, capPeriod: .monthly),
                CategoryReward(category: .travel, multiplier: 5, isPercentage: true, cap: 500, capPeriod: .monthly),
                CategoryReward(category: .transit, multiplier: 5, isPercentage: true, cap: 500, capPeriod: .monthly),
                CategoryReward(category: .streaming, multiplier: 5, isPercentage: true, cap: 500, capPeriod: .monthly),
                CategoryReward(category: .drugstore, multiplier: 5, isPercentage: true, cap: 500, capPeriod: .monthly),
                CategoryReward(category: .homeImprovement, multiplier: 5, isPercentage: true, cap: 500, capPeriod: .monthly),
                CategoryReward(category: .fitness, multiplier: 5, isPercentage: true, cap: 500, capPeriod: .monthly),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 200, bonusType: .cashback, spendRequirement: 1500, timeframeDays: 180, description: "$200 back after $1,500 in 6 months"),
            imageColor: "#003B70",
            imageURL: "https://www.citi.com/CRD/images/citi-custom-cash/citi-custom-cash_222x140.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "citi-premier",
            name: "Citi Premier",
            issuer: "Citi",
            network: .mastercard,
            annualFee: 95,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .dining, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .gas, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .travel, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 60000, bonusType: .points, spendRequirement: 4000, timeframeDays: 90, description: "60,000 points after $4,000 in 3 months"),
            imageColor: "#003B70",
            imageURL: "https://www.citi.com/CRD/images/citi-premier/citi-premier_222x140.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "citi-strata-premier",
            name: "Citi Strata Premier",
            issuer: "Citi",
            network: .mastercard,
            annualFee: 95,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 10, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .gas, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .streaming, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 75000, bonusType: .points, spendRequirement: 4000, timeframeDays: 90, description: "75,000 points after $4,000 in 3 months"),
            imageColor: "#003B70",
            imageURL: "https://www.citi.com/CRD/images/citi-strata-premier/citi-strata-premier_222x140.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "citi-rewards-plus",
            name: "Citi Rewards+",
            issuer: "Citi",
            network: .mastercard,
            annualFee: 0,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .grocery, multiplier: 2, isPercentage: false, cap: 6000, capPeriod: .yearly),
                CategoryReward(category: .gas, multiplier: 2, isPercentage: false, cap: 6000, capPeriod: .yearly),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 20000, bonusType: .points, spendRequirement: 1500, timeframeDays: 90, description: "20,000 points after $1,500 in 3 months"),
            imageColor: "#003B70",
            imageURL: "https://www.citi.com/CRD/images/citi-rewards-plus/citi-rewards-plus_222x140.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "citi-diamond-preferred",
            name: "Citi Diamond Preferred",
            issuer: "Citi",
            network: .mastercard,
            annualFee: 0,
            rewardType: .points,
            baseReward: 0,
            baseIsPercentage: false,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#003B70",
            imageURL: nil,
            lastUpdated: Date()
        ),
        CreditCard(
            id: "costco-anywhere-visa",
            name: "Costco Anywhere Visa",
            issuer: "Citi",
            network: .visa,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .gas, multiplier: 4, isPercentage: true, cap: 7000, capPeriod: .yearly),
                CategoryReward(category: .travel, multiplier: 3, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 3, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .wholesale, multiplier: 2, isPercentage: true, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#E31837",
            imageURL: "https://www.citi.com/CRD/images/costco-anywhere/costco-anywhere_222x140.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "citi-aadvantage-platinum",
            name: "Citi AAdvantage Platinum Select",
            issuer: "Citi",
            network: .mastercard,
            annualFee: 99,
            rewardType: .miles,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .gas, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 50000, bonusType: .miles, spendRequirement: 2500, timeframeDays: 90, description: "50,000 miles after $2,500 in 3 months"),
            imageColor: "#C8102E",
            imageURL: nil,
            lastUpdated: Date()
        ),
    ]

    // MARK: - Capital One Cards

    static let capitalOneCards: [CreditCard] = [
        CreditCard(
            id: "capital-one-savor",
            name: "Capital One Savor",
            issuer: "Capital One",
            network: .mastercard,
            annualFee: 95,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .dining, multiplier: 4, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .entertainment, multiplier: 4, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .streaming, multiplier: 4, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 3, isPercentage: true, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 300, bonusType: .cashback, spendRequirement: 3000, timeframeDays: 90, description: "$300 back after $3,000 in 3 months"),
            imageColor: "#D03027",
            imageURL: "https://ecm.capitalone.com/WCM/card/pages/open-graph/savorone.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "capital-one-savorone",
            name: "Capital One SavorOne",
            issuer: "Capital One",
            network: .mastercard,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .dining, multiplier: 3, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .entertainment, multiplier: 3, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .streaming, multiplier: 3, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 3, isPercentage: true, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 200, bonusType: .cashback, spendRequirement: 500, timeframeDays: 90, description: "$200 back after $500 in 3 months"),
            imageColor: "#D03027",
            imageURL: "https://ecm.capitalone.com/WCM/card/pages/open-graph/savorone.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "capital-one-venture-x",
            name: "Capital One Venture X",
            issuer: "Capital One",
            network: .visa,
            annualFee: 395,
            rewardType: .miles,
            baseReward: 2,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 10, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 75000, bonusType: .miles, spendRequirement: 4000, timeframeDays: 90, description: "75,000 miles after $4,000 in 3 months"),
            imageColor: "#000000",
            imageURL: "https://ecm.capitalone.com/WCM/card/pages/open-graph/venture-x.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "capital-one-venture",
            name: "Capital One Venture",
            issuer: "Capital One",
            network: .visa,
            annualFee: 95,
            rewardType: .miles,
            baseReward: 2,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 5, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 75000, bonusType: .miles, spendRequirement: 4000, timeframeDays: 90, description: "75,000 miles after $4,000 in 3 months"),
            imageColor: "#000000",
            imageURL: "https://ecm.capitalone.com/WCM/card/pages/open-graph/venture.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "capital-one-ventureone",
            name: "Capital One VentureOne",
            issuer: "Capital One",
            network: .visa,
            annualFee: 0,
            rewardType: .miles,
            baseReward: 1.25,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 5, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 20000, bonusType: .miles, spendRequirement: 500, timeframeDays: 90, description: "20,000 miles after $500 in 3 months"),
            imageColor: "#013B5E",
            imageURL: "https://ecm.capitalone.com/WCM/card/products/og/ventureone.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "capital-one-quicksilver",
            name: "Capital One Quicksilver",
            issuer: "Capital One",
            network: .mastercard,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1.5,
            baseIsPercentage: true,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 200, bonusType: .cashback, spendRequirement: 500, timeframeDays: 90, description: "$200 back after $500 in 3 months"),
            imageColor: "#013B5E",
            imageURL: "https://ecm.capitalone.com/WCM/card/pages/open-graph/quicksilver.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "capital-one-platinum",
            name: "Capital One Platinum",
            issuer: "Capital One",
            network: .mastercard,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 0,
            baseIsPercentage: true,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#013B5E",
            imageURL: "https://ecm.capitalone.com/WCM/card/pages/open-graph/platinumog.png",
            lastUpdated: Date()
        ),
    ]

    // MARK: - Discover Cards

    static let discoverCards: [CreditCard] = [
        CreditCard(
            id: "discover-it",
            name: "Discover it Cash Back",
            issuer: "Discover",
            network: .discover,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [],
            rotatingCategories: [
                RotatingCategory(quarter: 1, year: MockData.currentYear, categories: [.grocery, .drugstore], multiplier: 5, isPercentage: true, cap: 1500, activationRequired: true),
                RotatingCategory(quarter: 2, year: MockData.currentYear, categories: [.gas, .homeImprovement], multiplier: 5, isPercentage: true, cap: 1500, activationRequired: true),
                RotatingCategory(quarter: 3, year: MockData.currentYear, categories: [.dining, .paypal], multiplier: 5, isPercentage: true, cap: 1500, activationRequired: true),
                RotatingCategory(quarter: 4, year: MockData.currentYear, categories: [.amazon, .onlineShopping], multiplier: 5, isPercentage: true, cap: 1500, activationRequired: true),
            ],
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#FF6600",
            imageURL: "https://www.discover.com/content/dam/discover/en_us/credit-cards/card-acquisitions/grey-redesign/images/cardart/cardart-itnew-cli.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "discover-it-chrome",
            name: "Discover it Chrome",
            issuer: "Discover",
            network: .discover,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .gas, multiplier: 2, isPercentage: true, cap: 1000, capPeriod: .quarterly),
                CategoryReward(category: .dining, multiplier: 2, isPercentage: true, cap: 1000, capPeriod: .quarterly),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#A3A3A3",
            imageURL: "https://www.discover.com/content/dam/discover/en_us/credit-cards/card-acquisitions/grey-redesign/global/images/cardart/cardart-cash-chrome-platinum-620-382.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "discover-it-miles",
            name: "Discover it Miles",
            issuer: "Discover",
            network: .discover,
            annualFee: 0,
            rewardType: .miles,
            baseReward: 1.5,
            baseIsPercentage: false,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#FF6600",
            imageURL: "https://www.discover.com/content/dam/discover/en_us/credit-cards/card-acquisitions/grey-redesign/global/images/cardart/cardart-travel-beachcard-620-382.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "discover-it-student",
            name: "Discover it Student Cash Back",
            issuer: "Discover",
            network: .discover,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [],
            rotatingCategories: [
                RotatingCategory(quarter: 1, year: MockData.currentYear, categories: [.grocery, .drugstore], multiplier: 5, isPercentage: true, cap: 1500, activationRequired: true),
                RotatingCategory(quarter: 2, year: MockData.currentYear, categories: [.gas, .homeImprovement], multiplier: 5, isPercentage: true, cap: 1500, activationRequired: true),
                RotatingCategory(quarter: 3, year: MockData.currentYear, categories: [.dining, .paypal], multiplier: 5, isPercentage: true, cap: 1500, activationRequired: true),
                RotatingCategory(quarter: 4, year: MockData.currentYear, categories: [.amazon, .onlineShopping], multiplier: 5, isPercentage: true, cap: 1500, activationRequired: true),
            ],
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#FF6600",
            imageURL: "https://www.discover.com/content/dam/discover/en_us/credit-cards/card-acquisitions/grey-redesign/global/images/cardart/cardart-student-iridescent-390-243.png",
            lastUpdated: Date()
        ),
    ]

    // MARK: - Bank of America Cards

    static let boaCards: [CreditCard] = [
        CreditCard(
            id: "boa-customized-cash",
            name: "Bank of America Customized Cash",
            issuer: "Bank of America",
            network: .visa,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .grocery, multiplier: 2, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .wholesale, multiplier: 2, isPercentage: true, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: SelectableConfig(
                maxSelections: 1,
                availableCategories: [.gas, .onlineShopping, .dining, .travel, .drugstore, .homeImprovement],
                multiplier: 3,
                isPercentage: true,
                cap: 2500,
                capPeriod: .quarterly
            ),
            signUpBonus: SignUpBonus(bonusAmount: 200, bonusType: .cashback, spendRequirement: 1000, timeframeDays: 90, description: "$200 back after $1,000 in 90 days"),
            imageColor: "#E31837",
            imageURL: "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/8ckn_cshsigcm_v_250x158.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "boa-premium-rewards",
            name: "Bank of America Premium Rewards",
            issuer: "Bank of America",
            network: .visa,
            annualFee: 95,
            rewardType: .points,
            baseReward: 1.5,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 60000, bonusType: .points, spendRequirement: 4000, timeframeDays: 90, description: "60,000 points after $4,000 in 90 days"),
            imageColor: "#012169",
            imageURL: "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/8CAL_prmsigcm_v_250_158.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "boa-premium-rewards-elite",
            name: "Bank of America Premium Rewards Elite",
            issuer: "Bank of America",
            network: .visa,
            annualFee: 550,
            rewardType: .points,
            baseReward: 1.5,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 75000, bonusType: .points, spendRequirement: 5000, timeframeDays: 90, description: "75,000 points after $5,000 in 90 days"),
            imageColor: "#012169",
            imageURL: "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/8cud_premrewelite_v_250x158.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "boa-travel-rewards",
            name: "Bank of America Travel Rewards",
            issuer: "Bank of America",
            network: .visa,
            annualFee: 0,
            rewardType: .points,
            baseReward: 1.5,
            baseIsPercentage: false,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 25000, bonusType: .points, spendRequirement: 1000, timeframeDays: 90, description: "25,000 points after $1,000 in 90 days"),
            imageColor: "#012169",
            imageURL: "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/8blm_trvsigcm_v_250x158.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "boa-unlimited-cash",
            name: "Bank of America Unlimited Cash Rewards",
            issuer: "Bank of America",
            network: .visa,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1.5,
            baseIsPercentage: true,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 200, bonusType: .cashback, spendRequirement: 1000, timeframeDays: 90, description: "$200 back after $1,000 in 90 days"),
            imageColor: "#E31837",
            imageURL: "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/8cty_cshsigcm_v_250x157.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "boa-alaska-airlines",
            name: "Alaska Airlines Visa",
            issuer: "Bank of America",
            network: .visa,
            annualFee: 95,
            rewardType: .miles,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .gas, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .streaming, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 70000, bonusType: .miles, spendRequirement: 3000, timeframeDays: 90, description: "70,000 miles after $3,000 in 90 days"),
            imageColor: "#00274C",
            imageURL: "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/1bbt_sigcm_v_atmos_ascent_250.png",
            lastUpdated: Date()
        ),
    ]

    // MARK: - US Bank Cards

    static let usBankCards: [CreditCard] = [
        CreditCard(
            id: "us-bank-cash-plus",
            name: "US Bank Cash+",
            issuer: "US Bank",
            network: .visa,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: SelectableConfig(
                maxSelections: 2,
                availableCategories: [.gas, .grocery, .dining, .utilities, .streaming, .transit, .homeImprovement],
                multiplier: 5,
                isPercentage: true,
                cap: 2000,
                capPeriod: .quarterly
            ),
            signUpBonus: SignUpBonus(bonusAmount: 200, bonusType: .cashback, spendRequirement: 1000, timeframeDays: 120, description: "$200 back after $1,000 in 120 days"),
            imageColor: "#0C2340",
            imageURL: "https://www.usbank.com/content/dam/usbank/en/images/photos/credit-cards/photo-cash-plus-signature-lg.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "us-bank-altitude-go",
            name: "US Bank Altitude Go",
            issuer: "US Bank",
            network: .visa,
            annualFee: 0,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .dining, multiplier: 4, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .gas, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .streaming, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 25000, bonusType: .points, spendRequirement: 1000, timeframeDays: 90, description: "25,000 points after $1,000 in 90 days"),
            imageColor: "#0C2340",
            imageURL: "https://www.usbank.com/content/dam/usbank/en/images/illustrations/card-art/credit-cards/altitude-go-visa-signature-credit-card.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "us-bank-altitude-connect",
            name: "US Bank Altitude Connect",
            issuer: "US Bank",
            network: .visa,
            annualFee: 95,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 5, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .gas, multiplier: 4, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .evCharging, multiplier: 4, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .streaming, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 50000, bonusType: .points, spendRequirement: 2000, timeframeDays: 120, description: "50,000 points after $2,000 in 120 days"),
            imageColor: "#0C2340",
            imageURL: "https://www.usbank.com/content/dam/usbank/en/images/photos/credit-cards/photo-altitude-connect-consumer.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "us-bank-altitude-reserve",
            name: "US Bank Altitude Reserve",
            issuer: "US Bank",
            network: .visa,
            annualFee: 400,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 50000, bonusType: .points, spendRequirement: 4500, timeframeDays: 90, description: "50,000 points after $4,500 in 90 days"),
            imageColor: "#000000",
            imageURL: "https://www.usbank.com/content/dam/usbank/en/images/photos/credit-cards/photo-altitude-reserve-visa-infinite-benefits-vertical-card-art.png",
            lastUpdated: Date()
        ),
    ]

    // MARK: - Wells Fargo Cards

    static let wellsFargoCards: [CreditCard] = [
        CreditCard(
            id: "wells-fargo-active-cash",
            name: "Wells Fargo Active Cash",
            issuer: "Wells Fargo",
            network: .visa,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 2,
            baseIsPercentage: true,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 200, bonusType: .cashback, spendRequirement: 500, timeframeDays: 90, description: "$200 back after $500 in 3 months"),
            imageColor: "#D71E28",
            imageURL: "https://creditcards.wellsfargo.com/W-Card-MarketPlace/v12-17-25/images/Products/ActiveCash/WF_ActiveCash_VS_Collateral_Front_RGB.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "wells-fargo-autograph",
            name: "Wells Fargo Autograph",
            issuer: "Wells Fargo",
            network: .visa,
            annualFee: 0,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .dining, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .travel, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .gas, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .transit, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .streaming, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .phone, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 20000, bonusType: .points, spendRequirement: 1000, timeframeDays: 90, description: "20,000 points after $1,000 in 3 months"),
            imageColor: "#D71E28",
            imageURL: "https://www.wellsfargo.com/W-Card-MarketPlace/v12-17-25/images/Products/Autograph/Autograph-No-Fee-Card-RGB_d.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "wells-fargo-autograph-journey",
            name: "Wells Fargo Autograph Journey",
            issuer: "Wells Fargo",
            network: .visa,
            annualFee: 95,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .travel, multiplier: 5, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 4, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 60000, bonusType: .points, spendRequirement: 4000, timeframeDays: 90, description: "60,000 points after $4,000 in 3 months"),
            imageColor: "#D71E28",
            imageURL: "https://creditcards.wellsfargo.com/W-Card-MarketPlace/v12-17-25/images/Products/AutographJourney/WF_Autograph_Journey_Card_d.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "wells-fargo-reflect",
            name: "Wells Fargo Reflect",
            issuer: "Wells Fargo",
            network: .visa,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 0,
            baseIsPercentage: true,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#D71E28",
            imageURL: "https://creditcards.wellsfargo.com/W-Card-MarketPlace/v12-17-25/images/Products/Reflect/Reflect_homepage.png",
            lastUpdated: Date()
        ),
    ]

    // MARK: - Other Issuers

    static let otherCards: [CreditCard] = [
        CreditCard(
            id: "apple-card",
            name: "Apple Card",
            issuer: "Goldman Sachs",
            network: .mastercard,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .apple, multiplier: 3, isPercentage: true, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#F5F5F7",
            imageURL: "https://www.apple.com/v/apple-card/p/images/overview/icon_titanium__ex97ftuqz8mq_large.png",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "bilt-mastercard",
            name: "Bilt Mastercard",
            issuer: "Bilt",
            network: .mastercard,
            annualFee: 0,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .dining, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .travel, multiplier: 2, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#000000",
            imageURL: "https://static.biltrewards.com/assets/seo/bilt_card2_coming_soon_seo.jpg",
            lastUpdated: Date()
        ),
        CreditCard(
            id: "alliant-cashback",
            name: "Alliant Cashback Visa",
            issuer: "Alliant Credit Union",
            network: .visa,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 2.5,
            baseIsPercentage: true,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#003087",
            imageURL: nil,
            lastUpdated: Date()
        ),
        CreditCard(
            id: "penfed-platinum",
            name: "PenFed Platinum Rewards",
            issuer: "PenFed",
            network: .visa,
            annualFee: 0,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .gas, multiplier: 5, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#00467F",
            imageURL: nil,
            lastUpdated: Date()
        ),
        CreditCard(
            id: "navy-federal-more-rewards",
            name: "Navy Federal More Rewards",
            issuer: "Navy Federal",
            network: .visa,
            annualFee: 0,
            rewardType: .points,
            baseReward: 1,
            baseIsPercentage: false,
            categoryRewards: [
                CategoryReward(category: .dining, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .gas, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .grocery, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
                CategoryReward(category: .transit, multiplier: 3, isPercentage: false, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#003057",
            imageURL: nil,
            lastUpdated: Date()
        ),
        CreditCard(
            id: "paypal-cashback",
            name: "PayPal Cashback Mastercard",
            issuer: "Synchrony",
            network: .mastercard,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 2,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .paypal, multiplier: 3, isPercentage: true, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#003087",
            imageURL: nil,
            lastUpdated: Date()
        ),
        CreditCard(
            id: "venmo-credit-card",
            name: "Venmo Credit Card",
            issuer: "Synchrony",
            network: .visa,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .grocery, multiplier: 3, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .gas, multiplier: 2, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 2, isPercentage: true, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#3D95CE",
            imageURL: nil,
            lastUpdated: Date()
        ),
        CreditCard(
            id: "sofi-credit-card",
            name: "SoFi Credit Card",
            issuer: "SoFi",
            network: .mastercard,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 2,
            baseIsPercentage: true,
            categoryRewards: [],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#5F92D2",
            imageURL: nil,
            lastUpdated: Date()
        ),
        CreditCard(
            id: "target-redcard",
            name: "Target RedCard",
            issuer: "Target",
            network: .mastercard,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 0,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .target, multiplier: 5, isPercentage: true, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: nil,
            imageColor: "#CC0000",
            imageURL: nil,
            lastUpdated: Date()
        ),
        CreditCard(
            id: "walmart-rewards",
            name: "Walmart Rewards Card",
            issuer: "Capital One",
            network: .mastercard,
            annualFee: 0,
            rewardType: .cashback,
            baseReward: 1,
            baseIsPercentage: true,
            categoryRewards: [
                CategoryReward(category: .walmart, multiplier: 5, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .dining, multiplier: 2, isPercentage: true, cap: nil, capPeriod: nil),
                CategoryReward(category: .travel, multiplier: 2, isPercentage: true, cap: nil, capPeriod: nil),
            ],
            rotatingCategories: nil,
            selectableConfig: nil,
            signUpBonus: SignUpBonus(bonusAmount: 50, bonusType: .cashback, spendRequirement: 0, timeframeDays: 0, description: "$50 back on first purchase"),
            imageColor: "#0071CE",
            imageURL: nil,
            lastUpdated: Date()
        ),
    ]

    // MARK: - Combined Database

    static let creditCards: [CreditCard] =
        chaseCards +
        amexCards +
        citiCards +
        capitalOneCards +
        discoverCards +
        boaCards +
        usBankCards +
        wellsFargoCards +
        otherCards

    static func getCard(byId id: String) -> CreditCard? {
        creditCards.first { $0.id == id }
    }
}
